In [3]:
from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error, r2_score

In [37]:
hit = pd.read_csv("Hitters.csv")
df = hit.copy()
df = df.dropna()
dms = pd.get_dummies(df[['League', 'Division', 'NewLeague']])
y = df["Salary"]
X_ = df.drop(['Salary', 'League', 'Division', 'NewLeague'], axis=1).astype('float64')
X = pd.concat([X_, dms[['League_N', 'Division_W', 'NewLeague_N']]], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.25, 
                                                    random_state=42)



In [60]:
from sklearn.ensemble import BaggingRegressor

bag_model=BaggingRegressor(bootstrap_features=True)
bag_model.fit(X_train,y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=True,
                 max_features=1.0, max_samples=1.0, n_estimators=10,
                 n_jobs=None, oob_score=False, random_state=None, verbose=0,
                 warm_start=False)

In [39]:
bag_model.n_estimators

10

In [40]:
bag_model.estimators_   #different trees

[DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=388655174, splitter='best'),
 DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=1375400089, splitter='best'),
 DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_dec

In [41]:
bag_model.estimators_samples_

[array([ 46,  63,   4,  64,  41, 170,   9,  10, 106,  45,  49,  39, 173,
         35, 115, 121, 104,  48,  56,  85, 123, 122,  53,  52,  31,  57,
         18,  84, 109,  68,  36, 141,  18, 186, 118, 193,   4, 189, 183,
         81, 142,  29,  16, 154, 165,  64,  90, 173, 142,  45, 142,  88,
         35, 164,  81,  74, 161, 173,  66,  34, 136, 193, 145, 177, 119,
        173, 140, 192, 118, 177,  12,  28, 171,   0, 175,  12, 123, 193,
        163,  73,  98,  61,  30,  27,  92,   0, 108,  50,  93,  96, 189,
        142,  37, 118,  71, 166, 154, 121, 112, 113, 166, 168, 144,  21,
         30, 104, 103,  86,   9, 116,  80,  10,  87, 129, 181,  86,  78,
        130,  93, 170,  13,  33,   2, 143,  25,  70,  85, 185, 189,  31,
         68,  51,   8,  21, 105, 164, 164,  39,  47, 124,  98, 133, 154,
         45,  81, 137, 145, 194,  22, 193, 113, 135,  26, 171, 196, 154,
         69, 150, 130, 131,   1, 193,  32,   5, 110, 111, 176,  31, 138,
         97, 194,  18,   9,  25,  42,  81,  76,  91

In [42]:
bag_model.estimators_features_

[array([ 3, 17,  8,  8, 17,  8,  1,  2, 14,  1,  3,  5,  9, 10,  8,  2,  4,
        16, 14]),
 array([ 5, 14, 17, 10, 12,  0, 10, 17,  2,  6, 16,  1,  9,  1,  1, 16,  9,
         6,  1]),
 array([11, 11,  9, 17, 13, 13,  9,  3, 13, 11,  9, 17, 17,  3,  1, 11, 18,
        12,  5]),
 array([ 3, 13,  7, 16,  8, 13,  6, 13, 10,  6,  3, 11, 17, 18,  1,  0,  8,
        12,  6]),
 array([16,  6,  8, 12,  3,  7, 12, 16,  1, 16,  9, 16,  9, 17, 17, 11,  4,
         2, 12]),
 array([12, 14, 12,  8, 17, 15, 18, 13, 17,  6, 17,  4,  7,  5, 16, 15, 11,
        13,  5]),
 array([ 3, 15, 16, 15, 10,  4,  8,  5, 16, 18,  9,  5, 17, 12, 12, 17,  5,
         6,  2]),
 array([ 9, 12,  0, 11,  9, 16, 13, 16, 18, 14,  1, 18,  5,  9,  7, 12, 17,
         0,  9]),
 array([ 8, 12,  3, 13,  1,  2, 18, 18, 14, 14,  4, 10, 10, 15,  6, 16, 17,
        10,  1]),
 array([ 8,  7,  4, 12,  3,  6, 12,  1, 18, 10,  3, 10, 10, 10,  4, 17, 17,
        17, 14])]

In [43]:
bag_model.estimators_[0]

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=388655174, splitter='best')

# Prediction

In [61]:
import numpy as np
y_pred=bag_model.predict(X_test)

In [62]:
np.sqrt(mean_squared_error(y_test,y_pred))

354.934826827668

In [ ]:
#example

In [63]:
second_y_pred=bag_model.estimators_[1].fit(X_train,y_train).predict(X_test)

In [64]:
np.sqrt(mean_squared_error(second_y_pred,y_test))

478.5444088270242

# Model Tuning

In [66]:
bag_params={"n_estimators": range(2,20)}

In [67]:
bag_cv_model= GridSearchCV(bag_model, bag_params,cv=10)

In [69]:
bag_cv_model.fit(X_train,y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=BaggingRegressor(base_estimator=None, bootstrap=True,
                                        bootstrap_features=True,
                                        max_features=1.0, max_samples=1.0,
                                        n_estimators=10, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'n_estimators': range(2, 20)}, pre_dispatch='2*n_jobs',
             refit=True, return_train_score=False, scoring=None, verbose=0)

In [71]:
bag_cv_model.best_params_

{'n_estimators': 12}

In [72]:
bag_tuned=BaggingRegressor(n_estimators= 12,random_state=45)

In [74]:
bag_tuned.fit(X_train,y_train)

BaggingRegressor(base_estimator=None, bootstrap=True, bootstrap_features=False,
                 max_features=1.0, max_samples=1.0, n_estimators=12,
                 n_jobs=None, oob_score=False, random_state=45, verbose=0,
                 warm_start=False)

In [76]:
y_pred=bag_tuned.predict(X_test)
np.sqrt(mean_squared_error(y_pred,y_test))

349.06722149329255